steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg=VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg=VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "--build-arg=VITE_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
      - "--build-arg=VITE_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "--build-arg=VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/terrene-care/praxis/praxis-web:${_TAG}"
      - "."
images:
  - "asia-southeast1-docker.pkg.dev/terrene-care/praxis/praxis-web:${_TAG}"
substitutions:
  _TAG: latest
  _FIREBASE_API_KEY: ""
  _FIREBASE_AUTH_DOMAIN: ""
  _FIREBASE_PROJECT_ID: ""
  _FIREBASE_STORAGE_BUCKET: ""
  _FIREBASE_MESSAGING_SENDER_ID: ""
  _FIREBASE_APP_ID: ""
