# Copyright 2026 Terrene Foundation
# Licensed under the Apache License, Version 2.0
"""Shared fixtures for unit tests of the trust layer."""

import sqlite3
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


# ---------------------------------------------------------------------------
# Fast database isolation — bypass DataFlow workflow engine for table creation
# ---------------------------------------------------------------------------

# SQL matching the exact schema DataFlow produces — no Kailash workflow overhead.
# Generated by: PRAGMA table_info() on DataFlow-created tables.
_CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS sessions (id TEXT, workspace_id TEXT, domain TEXT, state TEXT, genesis_id TEXT, constraint_envelope TEXT, session_metadata TEXT, ended_at TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS deliberation_records (id TEXT, session_id TEXT, record_type TEXT, content TEXT, reasoning_trace TEXT, reasoning_hash TEXT, parent_record_id TEXT, anchor_id TEXT, actor TEXT, confidence REAL, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS constraint_events (id TEXT, session_id TEXT, action TEXT, resource TEXT, dimension TEXT, gradient_result TEXT, utilization REAL, resolved_by TEXT, resolution TEXT, resolved_at TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS trust_chain_entries (id TEXT, session_id TEXT, entry_type TEXT, payload TEXT, signature TEXT, signer_key_id TEXT, parent_hash TEXT, content_hash TEXT, verified INTEGER, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS workspaces (id TEXT, name TEXT, domain TEXT, constraint_template TEXT, constraint_config TEXT, genesis_key_id TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS held_actions (id TEXT, session_id TEXT, action TEXT, resource TEXT, dimension TEXT, verdict_payload TEXT, resolved INTEGER, resolved_by TEXT, resolution TEXT, resolved_at TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS learning_observations (id TEXT, session_id TEXT, domain TEXT, target TEXT, content TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS learning_patterns (id TEXT, domain TEXT, pattern_type TEXT, description TEXT, confidence REAL, evidence TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS learning_evolution_proposals (id TEXT, pattern_id TEXT, domain TEXT, proposal_type TEXT, target TEXT, current_value TEXT, proposed_value TEXT, rationale TEXT, status TEXT, reviewed_by TEXT, reviewed_at TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS users (id TEXT, email TEXT, display_name TEXT, photo_url TEXT, provider TEXT, role TEXT, last_login_at TEXT, created_at TEXT, updated_at TEXT);
"""


# Session-scoped DB: create ONE DataFlow instance for all unit tests.
# Per-test isolation is achieved by DELETE FROM all tables, not re-creating DataFlow.
_SESSION_DB_PATH = None
_SESSION_DB_INIT = False


@pytest.fixture(scope="session", autouse=True)
def _session_db(tmp_path_factory):
    """Create one shared database for the entire test session."""
    global _SESSION_DB_PATH, _SESSION_DB_INIT
    import os

    db_dir = tmp_path_factory.mktemp("praxis_db")
    db_path = db_dir / "shared_test.db"
    _SESSION_DB_PATH = str(db_path)

    os.environ["DATABASE_URL"] = f"sqlite:///{db_path}"
    os.environ["PRAXIS_API_SECRET"] = "test-secret-key"
    os.environ["PRAXIS_DEV_MODE"] = "true"
    os.environ["PRAXIS_KEY_DIR"] = str(db_dir / "keys")

    # Create tables with raw sqlite3 (fast)
    conn = sqlite3.connect(str(db_path))
    conn.executescript(_CREATE_TABLES_SQL)
    conn.close()

    # Initialize DataFlow singleton ONCE
    from praxis.persistence import _set_db_for_testing

    _set_db_for_testing(f"sqlite:///{db_path}")
    _SESSION_DB_INIT = True

    yield

    from praxis.persistence import reset_db
    from praxis.config import reset_config

    reset_db()
    reset_config()


_ALL_TABLES = [
    "sessions",
    "deliberation_records",
    "constraint_events",
    "trust_chain_entries",
    "workspaces",
    "held_actions",
    "learning_observations",
    "learning_patterns",
    "learning_evolution_proposals",
    "users",
]


@pytest.fixture(autouse=True)
def _isolated_db(tmp_path):
    """Clean all tables before each test for data isolation.

    Does NOT re-create DataFlow — just DELETEs rows. ~0.5ms per test.
    """
    import os

    os.environ["PRAXIS_KEY_DIR"] = str(tmp_path / "keys")

    # Clean all tables (fast — no DataFlow init)
    if _SESSION_DB_PATH:
        conn = sqlite3.connect(_SESSION_DB_PATH)
        for table in _ALL_TABLES:
            conn.execute(f"DELETE FROM {table}")
        conn.commit()
        conn.close()

    yield


class MockKeyManager:
    """Minimal key manager for unit tests."""

    def __init__(self):
        self._keys: dict[str, Ed25519PrivateKey] = {}

    def generate_key(self, key_id: str) -> str:
        self._keys[key_id] = Ed25519PrivateKey.generate()
        return key_id

    def sign(self, key_id: str, data: bytes) -> bytes:
        if key_id not in self._keys:
            raise KeyError(f"Key not found: {key_id}")
        return self._keys[key_id].sign(data)

    def verify(self, key_id: str, data: bytes, signature: bytes) -> bool:
        if key_id not in self._keys:
            raise KeyError(f"Key not found: {key_id}")
        try:
            self._keys[key_id].public_key().verify(signature, data)
            return True
        except Exception:
            return False

    def get_public_key(self, key_id: str):
        if key_id not in self._keys:
            raise KeyError(f"Key not found: {key_id}")
        return self._keys[key_id].public_key()

    def export_public_pem(self, key_id: str) -> str:
        from cryptography.hazmat.primitives import serialization

        pub = self.get_public_key(key_id)
        pem_bytes = pub.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        return pem_bytes.decode("utf-8")


@pytest.fixture
def key_manager():
    """Provide a key manager with a pre-generated test key."""
    try:
        from praxis.trust.keys import KeyManager
        import tempfile

        km = KeyManager(Path(tempfile.mkdtemp()))
        km.generate_key("test-key")
        return km
    except (ImportError, Exception):
        km = MockKeyManager()
        km.generate_key("test-key")
        return km


@pytest.fixture
def key_manager_factory():
    """Factory that creates fresh key managers on demand."""

    def _factory(*key_ids):
        try:
            from praxis.trust.keys import KeyManager
            import tempfile

            km = KeyManager(Path(tempfile.mkdtemp()))
            for kid in key_ids:
                km.generate_key(kid)
            return km
        except (ImportError, Exception):
            km = MockKeyManager()
            for kid in key_ids:
                km.generate_key(kid)
            return km

    return _factory


@pytest.fixture
def sample_constraints():
    """Standard 5-dimensional constraint envelope for testing."""
    return {
        "financial": {"max_spend": 1000.0},
        "operational": {"allowed_actions": ["read", "write", "execute"]},
        "temporal": {"max_duration_minutes": 120},
        "data_access": {"allowed_paths": ["/src", "/tests", "/docs"]},
        "communication": {"allowed_channels": ["internal", "email"]},
    }


@pytest.fixture
def tighter_constraints():
    """Constraints that are strictly tighter than sample_constraints."""
    return {
        "financial": {"max_spend": 500.0},
        "operational": {"allowed_actions": ["read", "write"]},
        "temporal": {"max_duration_minutes": 60},
        "data_access": {"allowed_paths": ["/src", "/tests"]},
        "communication": {"allowed_channels": ["internal"]},
    }


@pytest.fixture
def looser_constraints():
    """Constraints that are LOOSER than sample_constraints (should fail tightening)."""
    return {
        "financial": {"max_spend": 2000.0},
        "operational": {"allowed_actions": ["read", "write", "execute", "deploy"]},
        "temporal": {"max_duration_minutes": 240},
        "data_access": {"allowed_paths": ["/src", "/tests", "/docs", "/secrets"]},
        "communication": {"allowed_channels": ["internal", "email", "external"]},
    }
